### ISSUE TITLE
Eval code available?

### ISSUE THREAD

**Issue by natsunoshion** [Leon1207/Video-RAG-master#1]
Hi author, I'm interested in this work and wonder how can I evaluate this model?

**Comment by Leon1207** [comment]
> Hi author, I'm interested in this work and wonder how can I evaluate this model?

Hi, happy to hear that you are interested in our work! We only proposed a pipeline but not a model, so that you can integrate it into any LVLMs and use the official evaluation code in any video benchmarks, like Video-MME (https://github.com/BradyFU/Video-MME)!

**Comment by Leon1207** [comment]
> Hi author, I'm interested in this work and wonder how can I evaluate this model?

Here we provide an example of evaluate Video-MME: https://github.com/Leon1207/Video-RAG-master/tree/main/evals

**Comment by natsunoshion** [comment]
Thank you for the clarification and the example!
