### ISSUE TITLE
A question in the code

### ISSUE THREAD

**Issue by whu125** [Leon1207/Video-RAG-master#2]
**Thank you for your excellent work! While using your framework for LLAVA inference, I noticed something strange.**

During inference, in the `llava_qwen` file:

```python
position_ids = kwargs.pop("position_ids", None)
attention_mask = kwargs.pop("attention_mask", None)
```

The extracted values are **None**, and I didn't see any values passed into kwargs. Could this be an issue with the code, or is it a problem on my end? I would greatly appreciate any guidance you can provide.

**Comment by Leon1207** [comment]
Maybe you can first debug try without our pipeline in pure LLaVA!

**Comment by whu125** [comment]
Perhaps you can check the `llava_inference` function in `vidrag_pipeline.py`:

```python
cont = model.generate(
    input_ids,
    images=video,
    modalities=["video"],
    do_sample=False,
    temperature=0,
    max_new_tokens=4096,
)
It doesn't seem to pass the necessary kwargs required by the generate function.

**Comment by Leon1207** [comment]
Please make sure you use the LLaVA-NeXT github: https://github.com/LLaVA-VL/LLaVA-NeXT
You can also refer to the inference code of LLaVA-Video here: https://huggingface.co/lmms-lab/LLaVA-Video-72B-Qwen2

**Comment by whu125** [comment]
OK，I will check carefully.Thank you.



---Original---
From: "Yongdong ***@***.***&gt;
Date: Tue, Dec 10, 2024 22:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Leon1207/Video-RAG-master] A question in the code (Issue #2)




 
Please make sure you use the LLaVA-NeXT github: https://github.com/LLaVA-VL/LLaVA-NeXT
 You can also refer to the inference code of LLaVA-Video here: https://huggingface.co/lmms-lab/LLaVA-Video-72B-Qwen2

**Comment by whu125** [comment]
Sorry, I raised this issue because my model output only includes an exclamation mark. It should be a problem with weight loading, and your pipeline is indeed the same as the official one. Apologies for the trouble caused.
